export const FETCH_PHOTOS_PENDING = 'FETCH_PHOTOS_PENDING';
export const FETCH_PHOTOS_FULFILLED = 'FETCH_PHOTOS_FULFILLED';
export const FETCH_PHOTOS_FAILED = 'FETCH_PHOTOS_FAILED';
export const REFRESH_PHOTOS_PENDING = 'REFRESH_PHOTOS_PENDING';
export const REFRESH_PHOTOS_FULFILLED = 'REFRESH_PHOTOS_FULFILLED';
export const REFRESH_PHOTOS_FAILED = 'REFRESH_PHOTOS_FAILED';
